library(ggplot2)
library(gridExtra)
library(latex2exp)
library(lattice)

beta1.plot <- ggplot(beta1.plot.data,aes(dp1))+geom_line(linetype = "twodash",size = 0.2,aes(y=beta.1.mean,colour="estimated_curve"))+geom_line(size = 0.2,aes(y=beta.true.1,colour="true_curve"))+geom_line(linetype = 2,size = 0.3,aes(y= beta.1.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=beta.1.lower,colour ="lower_curve"))+ xlab("U") + ylab(TeX("$\\beta_1(u)$"))+xlim(0.1, 0.9)+ylim(0, 1.3)+ scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
beta2.plot <- ggplot(beta2.plot.data, aes(dp1))+geom_line(linetype = "twodash",size = 0.2,aes(y=beta.true.2,colour="true_curve"))+geom_line(size = 0.2,aes(y=beta.2.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=beta.2.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=beta.2.lower,colour ="lower_curve"))+xlab("U") + ylab(TeX("$\\beta_1(u)$"))+xlim(0.1, 0.9)+ylim(-1.5, 1.5)+ scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
g.plot <- ggplot(g.plot.data,aes(dp2))+geom_line(size = 0.2,aes(y=g.true,colour="true_curve"))+geom_line(linetype = "twodash",size = 0.2,aes(y=g.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=g.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=g.lower,colour ="lower_curve"))+ xlab("z") + ylab(TeX("$g(z)$"))+xlim(-1.1, 1.1)+ylim(0.1, 0.9)+scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
V.plot <- ggplot(Variance.plot.data,aes(dp3))+geom_line(size = 0.2,aes(y=Variance.true,colour="true_curve"))+geom_line(linetype = "twodash",size = 0.2,aes(y=Variance.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=Variance.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=Variance.lower,colour ="lower_curve"))+ xlab(TeX("$\\mu$")) + ylab(TeX("$V(\\mu)$"))+xlim(0.35, 0.65)+ylim(0.22, 0.26)+scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
