library(ggplot2)
library(gridExtra)
library(latex2exp)
library(lattice)

beta1.plot <- ggplot(beta1.plot.data,aes(dp1))+geom_line(linetype = "twodash",size = 0.2,aes(y=beta.1.mean,colour="estimated_curve"))+geom_line(size = 0.2,aes(y=beta.true.1,colour="true_curve"))+geom_line(linetype = 2,size = 0.3,aes(y= beta.1.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=beta.1.lower,colour ="lower_curve"))+ xlab("U") + ylab(TeX("$\\beta_1(u)$"))+xlim(0.1, 0.9)+ylim(0.4, 0.9)+ scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
beta2.plot <- ggplot(beta2.plot.data, aes(dp1))+geom_line(size = 0.2,aes(y=beta.true.2,colour="true_curve"))+geom_line(linetype = "twodash",size = 0.2,aes(y=beta.2.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=beta.2.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=beta.2.lower,colour ="lower_curve"))+xlab("U") + ylab(TeX("$\\beta_2(u)$"))+xlim(0.1, 0.9)+ylim(0, 1)+ scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
#+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
beta3.plot <- ggplot(beta3.plot.data, aes(dp1))+geom_line(size = 0.2,aes(y=beta.true.3,colour="true_curve"))+geom_line(linetype = "twodash",size = 0.2,aes(y=beta.3.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=beta.3.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=beta.3.lower,colour ="lower_curve"))+xlab("U") + ylab(TeX("$\\beta_3(u)$"))+xlim(0.1, 0.9)+ylim(-0.5, 1)+ scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
g.plot <- ggplot(g.plot.data,aes(dp2))+geom_line(size = 0.2,aes(y=g.true,colour="true_curve"))+geom_line(linetype = "twodash",size = 0.2,aes(y=g.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=g.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=g.lower,colour ="lower_curve"))+ xlab("z") + ylab("g(z)")+xlim(-1, 1)+ylim(-1.4, 1.4)+scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")
V.plot <- ggplot(V.plot.data,aes(dp3))+geom_line(size = 0.2,aes(y=V.true,colour="true_curve"))+geom_line(linetype = "twodash",size = 0.2,aes(y=V.mean,colour="estimated_curve"))+geom_line(linetype = 2,size = 0.3,aes(y=V.upper,colour = "upper_curve"))+geom_line(size = 0.3,linetype = 2,aes(y=V.lower,colour ="lower_curve"))+ xlab("z") + ylab(TeX("$V(\\mu)$"))+xlim(-0.85, 0.85)+ylim(-0.1, 0.15)+scale_colour_manual(values= c("true_curve" = "#212121","estimated_curve" = "#212121", "upper_curve" = "#212121","lower_curve" = "#212121"))+theme(legend.position="none")+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),panel.background = element_blank(),panel.border = element_rect(fill = NA,colour = "black"),legend.position="none")

a <- grid.arrange(beta1.plot,beta2.plot,beta3.plot,g.plot,V.plot,nrow = 5)
